index:
    path: /
    controller: App\Controller\ContactController::index

contact_form:
    path: /contact
    controller: App\Controller\ContactController::new
form_success:
    path: /success
    controller: App\Controller\ContactController::success
